### ISSUE TITLE
Get java.lang.NullPointerException  during OIDC issuer discover

### ISSUE THREAD

**Issue by konvergence** [inversoft/restify#11]
Hi,

Fusionauth uses your lib to validate the OIDC Discover URL.

I got this error on authmfappd.web.bpifrance.fr, but no error on authmfa.web.bpifrance.fr.
I put the 2 HAR files, but I don't understand the difference.

```
2024-08-19 01:20:49.723 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "name" is null
	at com.inversoft.http.Cookie.addAttribute(Cookie.java:192)
	at com.inversoft.http.Cookie.fromResponseHeader(Cookie.java:178)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.inversoft.rest.ClientResponse.setHeaders(ClientResponse.java:129)
	at com.inversoft.rest.RESTClient.go(RESTClient.java:410)
```

**Comment by konvergence** [comment]
We finally found the reason.
The url /well-known/openid-configuration gave a cookie with a ; at the end of its value. This is not tolerated by the restify library.

**Comment by Jank1310** [comment]
We also encountering this issue, unfortunately the WAF of one of our customers is returning a malformed Set-Cookie Header which cannot be changed from our side :/
Maybe the library could accept an empty cookie-av and just ignore it?

**Comment by robotdan** [comment]
Thanks for reporting and confirming @konvergence and @Jank1310 - sorry about this, and for the delay. 

I have taken the PR @konvergence opened and expanded it a bit based on some other edge cases we've fixed in cookie parsing in https://github.com/fusionauth/java-http. 

- https://github.com/inversoft/restify/pull/14

The fix will then be pulled into FusionAuth via https://github.com/FusionAuth/fusionauth-issues/issues/2978.
